### ISSUE TITLE
Windows phone support

### ISSUE THREAD

**Issue by bewam** [MobileChromeApps/zip#26]
Hello,

My brother and I want to develop a portable app for kids using cordova. The app will need some decompression in it. It would be the only platform plugin we would use.
Javascript may be too slow.
Do you know how to decompress in windows 8 through cordova ? Will MobileChromeApps/zip have a windows support (featured) ?

Thanks for developing.

**Comment by mmocny** [comment]
We are not working on this, nor do we have plans to add support.  We would entertain accepting pull requests for this (though since we wouldn't provide ongoing support for the platform, we may not even do that).

If you would like unzip on platforms other than ios/android, you are better served to look elsewhere or implement yourself.

Sorry.
